from pathlib import Path
p=Path('index.html')
text=p.read_text(encoding='utf-8')

def rep(old,new,label):
    global text
    if old not in text:
        raise SystemExit(f'anchor missing: {label}')
    text=text.replace(old,new,1)

rep('<div class="turn-label"><b>Tour <span id="turnEconomyView">1</span></b></div>','<div class="turn-label"><b>Tour <span id="turnEconomyView">1</span></b><span class="turn-damage">💥 <span id="turnDamageView">0</span> dégâts</span></div>','turn label')
rep('.turn-label{display:flex;align-items:center;justify-content:center;min-width:78px;min-height:54px;padding:7px 10px;border:1px solid #5b4a35;border-radius:9px;background:linear-gradient(180deg,#201a13,#12100d);color:#f0c36d}', '.turn-label{display:flex;align-items:center;justify-content:center;min-width:78px;min-height:54px;padding:7px 10px;border:1px solid #5b4a35;border-radius:9px;background:linear-gradient(180deg,#201a13,#12100d);color:#f0c36d;flex-direction:column;gap:3px}.turn-damage{font-size:11px;color:#ffd9a0;white-space:nowrap}', 'turn css')
rep('.label-mini{display:block;font-size:11px;color:var(--muted);margin-bottom:3px}', '.label-mini{display:block;font-size:11px;color:var(--muted);margin-bottom:3px}.damage-check{display:flex;align-items:center;gap:7px;min-height:44px;padding:8px 10px;border:1px solid #444b5e;border-radius:8px;background:#0b0d12;color:var(--ivory);font-size:13px}.damage-check input{width:18px;height:18px}', 'damage css')
rep("actionUsed:false,actionKind:'',actionLabel:'',attackCount:0,bonusUsed:false,bonusLabel:'',bonusSpell:false,reactionUsed:false,reactionLabel:'',pendingHit:null,eldritchRun:null", "actionUsed:false,actionKind:'',actionLabel:'',attackCount:0,bonusUsed:false,bonusLabel:'',bonusSpell:false,reactionUsed:false,reactionLabel:'',pendingHit:null,eldritchRun:null,turnDamage:0,turnEvents:[]", 'state')
rep("function resetEconomy(){S.actionUsed=false;S.actionKind='';S.actionLabel='';S.attackCount=0;S.bonusUsed=false;S.bonusLabel='';S.bonusSpell=false;S.reactionUsed=false;S.reactionLabel=''}", "function resetEconomy(){S.actionUsed=false;S.actionKind='';S.actionLabel='';S.attackCount=0;S.bonusUsed=false;S.bonusLabel='';S.bonusSpell=false;S.reactionUsed=false;S.reactionLabel=''}\nfunction addTurnDamage(amount,label){amount=Math.max(0,Number(amount)||0);if(!amount)return;S.turnDamage=(S.turnDamage||0)+amount;if(!Array.isArray(S.turnEvents))S.turnEvents=[];S.turnEvents.push(`${label} : ${amount}`)}\nfunction resetTurnSummary(){S.turnDamage=0;S.turnEvents=[]}\nfunction endTurnSummary(){const action=S.actionUsed?(S.actionKind==='attack'?`${S.attackCount}/2 attaques`:(S.actionLabel||'utilisée')):'disponible';const bonus=S.bonusUsed?(S.bonusLabel||'utilisée'):'disponible';const reaction=S.reactionUsed?(S.reactionLabel||'utilisée'):'disponible';const events=(S.turnEvents&&S.turnEvents.length)?`\\n${S.turnEvents.join('\\n')}`:'';return `⏱ Fin du tour ${S.turn}\\n💥 Dégâts infligés : ${S.turnDamage||0}\\n⚔ Action : ${action}\\n✦ Bonus : ${bonus}\\n↯ Réaction : ${reaction}${events}`}", 'summary helpers')
rep("if(t)t.textContent=S.turn;", "if(t)t.textContent=S.turn;const td=q('#turnDamageView');if(td)td.textContent=S.turnDamage||0;", 'render damage')
rep("const dmg=w.total+elem.total+extra;if(sun){S.solHit=true;S.solTarget=S.currentTarget}else{S.selHit=true;S.selTarget=S.currentTarget}", "const dmg=w.total+elem.total+extra;addTurnDamage(dmg,sun?'Solinar':'Sélhane');if(sun){S.solHit=true;S.solTarget=S.currentTarget}else{S.selHit=true;S.selTarget=S.currentTarget}", 'blade dmg')
rep("sealText=`\\n✦ SCEAU D’ÉCLIPSE : +${r} radiant +${p} psychique = +${r+p} • avantage jusqu’à fin tour ${S.sealExpiresAfterTurn}`;fx('eclipse')", "addTurnDamage(r+p,'Sceau d’Éclipse');sealText=`\\n✦ SCEAU D’ÉCLIPSE : +${r} radiant +${p} psychique = +${r+p} • avantage jusqu’à fin tour ${S.sealExpiresAfterTurn}`;fx('eclipse')", 'seal dmg')
rep("const damage=w.total+elem.total+extra;\n const total=damage+sealDamage;", "const damage=w.total+elem.total+extra;\n addTurnDamage(damage,sun?'Solinar':'Sélhane');\n if(sealDamage)addTurnDamage(sealDamage,'Sceau d’Éclipse');\n const total=damage+sealDamage;", 'confirmed blade dmg')
rep("run.total+=r.total;\n   run.lines.push(`Rayon ${i} : Attaque ${attack} → TOUCHÉ${crit?' CRITIQUE':''} • Dégâts ${r.total}${run.cursed?' (Malédiction +4)':''}`);", "run.total+=r.total;\n   addTurnDamage(r.total,`Décharge occulte — rayon ${i}`);\n   run.lines.push(`Rayon ${i} : Attaque ${attack} → TOUCHÉ${crit?' CRITIQUE':''} • Dégâts ${r.total}${run.cursed?' (Malédiction +4)':''}`);", 'eldritch direct')
rep("run.total+=r.total;\n   run.lines.push(`Rayon ${p.ray} : Attaque ${p.total} → TOUCHÉ • Dégâts ${r.total}${run.cursed?' (Malédiction +4)':''}`);", "run.total+=r.total;\n   addTurnDamage(r.total,`Décharge occulte — rayon ${p.ray}`);\n   run.lines.push(`Rayon ${p.ray} : Attaque ${p.total} → TOUCHÉ • Dégâts ${r.total}${run.cursed?' (Malédiction +4)':''}`);", 'eldritch confirm')
rep("q('#newTurn').onclick=()=>{push();S.turn++;S.solHit=S.selHit=S.seal=false;S.solTarget=S.selTarget='';S.pendingHit=null;S.eldritchRun=null;S.lastCrit=false;S.lastCritBlade='';resetEconomy();if(S.sealTarget&&S.turn>S.sealExpiresAfterTurn){log(`✦ Le Sceau d’Éclipse sur ${S.sealTarget} expire.`);S.sealTarget='';S.sealExpiresAfterTurn=0}render();log(`↻ Tour ${S.turn} : Action, action bonus et réaction restaurées • suivi des touches réinitialisé.`)};", "q('#newTurn').onclick=()=>{push();const summary=endTurnSummary();S.turn++;S.solHit=S.selHit=S.seal=false;S.solTarget=S.selTarget='';S.pendingHit=null;S.eldritchRun=null;S.lastCrit=false;S.lastCritBlade='';resetEconomy();resetTurnSummary();if(S.sealTarget&&S.turn>S.sealExpiresAfterTurn){S.sealTarget='';S.sealExpiresAfterTurn=0}render();log(`${summary}\\n\\n↻ Tour ${S.turn} : Action, action bonus et réaction restaurées.`)};", 'new turn')
rep("S.lastCrit=false;S.turn=1;resetEconomy();render();", "S.lastCrit=false;S.turn=1;resetEconomy();resetTurnSummary();render();", 'new combat reset')
old_html='''<section class="panel" data-panel="defense"><div class="grid two">\n<article class="card" id="hexArmorCard"><div class="action-title">Armure des maléfices</div><div class="meta">Uniquement contre la <b>cible maudite</b> : sur 4–6 au d6, l’attaque qui t’a touché est annulée.</div><div class="row"><input id="incomingDamage" class="compact-input" style="max-width:120px" type="number" min="0" placeholder="Dégâts"><button id="hexArmor">Touché par la cible maudite</button><button id="applyDamage">Appliquer dégâts</button></div></article>\n<article class="card"><div class="action-title">Tombeau de Lazarus</div>'''
new_html='''<section class="panel" data-panel="defense"><div class="grid two">\n<article class="card golden" id="incomingDamageCard"><div class="action-title">🛡 Dégâts reçus</div><div class="meta">Traitement automatique : PV temporaires → PV • Armure d’Agathys si l’attaque est au corps-à-corps • test de concentration si nécessaire.</div><div class="row"><input id="incomingDamage" class="compact-input" style="max-width:130px" type="number" min="0" placeholder="Dégâts reçus"><label class="damage-check"><input id="incomingMelee" type="checkbox"> Attaque au CàC</label><button id="applyDamage" class="btn-gold">Appliquer</button></div><div class="meta">Le DD de concentration est calculé automatiquement : max(10, moitié des dégâts).</div></article>\n<article class="card" id="hexArmorCard"><div class="action-title">Armure des maléfices</div><div class="meta">Uniquement contre la <b>cible maudite</b> : sur 4–6 au d6, l’attaque est annulée. Sinon, les dégâts sont traités automatiquement avec le même système.</div><div class="row"><input id="hexIncomingDamage" class="compact-input" style="max-width:120px" type="number" min="0" placeholder="Dégâts"><label class="damage-check"><input id="hexIncomingMelee" type="checkbox"> CàC</label><button id="hexArmor">Tester</button></div></article>\n<article class="card"><div class="action-title">Tombeau de Lazarus</div>'''
rep(old_html,new_html,'defense html')
start=text.find("function applyIncomingDamage(amount,source='dégâts'){")
end=text.find('function concentrationSave(dmg){',start)
if start<0 or end<0: raise SystemExit('damage functions missing')
text=text[:start]+'''function rollConcentrationCheck(dmg){\n dmg=Math.max(0,Number(dmg)||0);\n if(!S.conc)return null;\n const dc=Math.max(10,Math.floor(dmg/2));\n const a=d(20)+3,b=d(20)+3,best=Math.max(a,b),ok=best>=dc;\n const spell=S.concSpell||'Concentration';\n if(!ok){S.conc=false;S.concSpell='';S.shroud=false}\n return {dc,a,b,best,ok,spell};\n}\nfunction processIncomingDamage(amount,{source='dégâts reçus',melee=false}={}){\n amount=Math.max(0,Number(amount)||0);if(!amount)return log('ℹ️ Aucun dégât à appliquer.');\n push();\n const agathysTriggers=!!(melee && S.agathys && S.tempHp>0 && S.tempSource===\"Armure d’Agathys\");\n const agathysDamage=agathysTriggers?(S.agathysDamage||25):0;\n let left=amount,absorbed=0;\n const tempBefore=S.tempHp||0;\n const tempSourceBefore=S.tempSource||'';\n if(S.tempHp>0){absorbed=Math.min(S.tempHp,left);S.tempHp-=absorbed;left-=absorbed;if(S.tempHp===0){if(S.tempSource===\"Armure d’Agathys\")S.agathys=false;S.tempSource=''}}\n const hpLoss=Math.min(S.hp,left);\n if(left>0)S.hp=Math.max(0,S.hp-left);\n const conc=rollConcentrationCheck(amount);\n render();\n let lines=[`🛡 ${source} : ${amount}`,`PV temp : ${absorbed?`-${absorbed}${tempSourceBefore?` (${tempSourceBefore})`:''}`:'0'}${tempBefore?` • reste ${S.tempHp}`:''}`,`PV perdus : ${hpLoss}`,`PV restants : ${S.hp}/${S.maxHp}`];\n if(agathysTriggers)lines.push(`❄ Armure d’Agathys : ${agathysDamage} dégâts de froid à l’attaquant`);\n if(conc){lines.push(`◐ Concentration DD ${conc.dc} : ${conc.a} / ${conc.b} → ${conc.best} ${conc.ok?'✅ MAINTENUE':'❌ PERDUE'}`);if(!conc.ok)lines.push(`${conc.spell} prend fin.`)}\n log(lines.join('\\n'));\n}\nfunction applyIncomingDamage(amount,source='dégâts reçus'){processIncomingDamage(amount,{source,melee:false});}\n'''+text[end:]
old_handlers="""q('#agathysHit').onclick=()=>{if(S.agathys&&S.tempHp>0&&S.tempSource===\"Armure d’Agathys\")log(`❄ Armure d’Agathys : la créature qui vient de toucher Kentaro au corps-à-corps subit ${S.agathysDamage} dégâts de froid.`);else log('ℹ️ Armure d’Agathys n’est pas active avec ses PV temporaires.')};\nq('#hexArmor').onclick=()=>{if(!S.curse||!cleanName(S.curseTarget))return log('❌ Aucune cible maudite active.');if(!useReaction('Armure des maléfices'))return render();render();const x=d(6),amt=Number(q('#incomingDamage').value)||0;if(x>=4)log(`🛡 Armure des maléfices contre ${S.curseTarget} : d6=${x} → ATTAQUE ANNULÉE. Aucun dégât appliqué.`);else{log(`🛡 Armure des maléfices : d6=${x} → attaque non annulée.`);if(amt>0)applyIncomingDamage(amt,'attaque de la cible maudite')}};\nq('#applyDamage').onclick=()=>applyIncomingDamage(Number(q('#incomingDamage').value)||0,'dégâts reçus');"""
new_handlers="""q('#agathysHit').onclick=()=>{if(S.agathys&&S.tempHp>0&&S.tempSource===\"Armure d’Agathys\")log(`❄ Armure d’Agathys est active : utilise le bloc « Dégâts reçus » de Défense et coche « Attaque au CàC » pour appliquer automatiquement son retour de ${S.agathysDamage} froid.`);else log('ℹ️ Armure d’Agathys n’est pas active avec ses PV temporaires.')};\nq('#hexArmor').onclick=()=>{if(!S.curse||!cleanName(S.curseTarget))return log('❌ Aucune cible maudite active.');if(!useReaction('Armure des maléfices'))return render();render();const x=d(6),amt=Number(q('#hexIncomingDamage').value)||0,melee=!!q('#hexIncomingMelee').checked;if(x>=4)log(`🛡 Armure des maléfices contre ${S.curseTarget} : d6=${x} → ATTAQUE ANNULÉE. Aucun dégât appliqué.`);else{log(`🛡 Armure des maléfices : d6=${x} → attaque non annulée.`);if(amt>0)processIncomingDamage(amt,{source:'attaque de la cible maudite',melee})}};\nq('#applyDamage').onclick=()=>processIncomingDamage(Number(q('#incomingDamage').value)||0,{source:'dégâts reçus',melee:!!q('#incomingMelee').checked});"""
rep(old_handlers,new_handlers,'defense handlers')
p.write_text(text,encoding='utf-8')
print('patched',len(text))
