from pathlib import Path
p=Path('index.html')
text=p.read_text(encoding='utf-8')

def rep(old,new,label):
    global text
    if old not in text: raise SystemExit('ANCHOR_MISSING:'+label)
    text=text.replace(old,new,1)

rep('<div class="turn-label"><b>Tour <span id="turnEconomyView">1</span></b></div>', '<div class="turn-label"><b>Tour <span id="turnEconomyView">1</span></b><span class="turn-damage">💥 <span id="turnDamageView">0</span> dégâts</span></div>', 'turn_label')
rep('.turn-label{display:flex;align-items:center;justify-content:center;min-width:78px;min-height:54px;padding:7px 10px;border:1px solid #5b4a35;border-radius:9px;background:linear-gradient(180deg,#201a13,#12100d);color:#f0c36d}', '.turn-label{display:flex;align-items:center;justify-content:center;min-width:78px;min-height:54px;padding:7px 10px;border:1px solid #5b4a35;border-radius:9px;background:linear-gradient(180deg,#201a13,#12100d);color:#f0c36d;flex-direction:column;gap:3px}.turn-damage{font-size:11px;color:#ffd9a0;white-space:nowrap}', 'css')
rep("actionUsed:false,actionKind:'',actionLabel:'',attackCount:0,bonusUsed:false,bonusLabel:'',bonusSpell:false,reactionUsed:false,reactionLabel:''", "actionUsed:false,actionKind:'',actionLabel:'',attackCount:0,bonusUsed:false,bonusLabel:'',bonusSpell:false,reactionUsed:false,reactionLabel:'',turnDamage:0,turnEvents:[]", 'state')
rep("function resetEconomy(){S.actionUsed=false;S.actionKind='';S.actionLabel='';S.attackCount=0;S.bonusUsed=false;S.bonusLabel='';S.bonusSpell=false;S.reactionUsed=false;S.reactionLabel=''}", "function resetEconomy(){S.actionUsed=false;S.actionKind='';S.actionLabel='';S.attackCount=0;S.bonusUsed=false;S.bonusLabel='';S.bonusSpell=false;S.reactionUsed=false;S.reactionLabel=''}\nfunction addTurnDamage(amount,label){amount=Math.max(0,Number(amount)||0);if(!amount)return;S.turnDamage=(S.turnDamage||0)+amount;if(!Array.isArray(S.turnEvents))S.turnEvents=[];S.turnEvents.push(`${label} : ${amount}`)}\nfunction resetTurnSummary(){S.turnDamage=0;S.turnEvents=[]}\nfunction endTurnSummary(){const action=S.actionUsed?(S.actionKind==='attack'?`${S.attackCount}/2 attaques`:(S.actionLabel||'utilisée')):'disponible';const bonus=S.bonusUsed?(S.bonusLabel||'utilisée'):'disponible';const reaction=S.reactionUsed?(S.reactionLabel||'utilisée'):'disponible';const events=(S.turnEvents&&S.turnEvents.length)?`\\n${S.turnEvents.join('\\n')}`:'';return `⏱ Fin du tour ${S.turn}\\n💥 Dégâts infligés : ${S.turnDamage||0}\\n⚔ Action : ${action}\\n✦ Bonus : ${bonus}\\n↯ Réaction : ${reaction}${events}`}", 'helpers')
rep("function renderEconomy(){", "function renderEconomy(){const td=q('#turnDamageView');if(td)td.textContent=S.turnDamage||0;", 'render')
rep("const dmg=w.total+elem.total+extra;if(sun){S.solHit=true;S.solTarget=S.currentTarget}else{S.selHit=true;S.selTarget=S.currentTarget}", "const dmg=w.total+elem.total+extra;addTurnDamage(dmg,sun?'Solinar':'Sélhane');if(sun){S.solHit=true;S.solTarget=S.currentTarget}else{S.selHit=true;S.selTarget=S.currentTarget}", 'blade_auto')
rep("sealText=`\\n✦ SCEAU D’ÉCLIPSE : +${r} radiant +${p} psychique = +${r+p} • avantage jusqu’à fin tour ${S.sealExpiresAfterTurn}`;fx('eclipse')", "addTurnDamage(r+p,'Sceau d’Éclipse');sealText=`\\n✦ SCEAU D’ÉCLIPSE : +${r} radiant +${p} psychique = +${r+p} • avantage jusqu’à fin tour ${S.sealExpiresAfterTurn}`;fx('eclipse')", 'seal')
rep("const damage=w.total+elem.total+extra;\n const total=damage+sealDamage;", "const damage=w.total+elem.total+extra;\n addTurnDamage(damage,sun?'Solinar':'Sélhane');\n if(sealDamage)addTurnDamage(sealDamage,'Sceau d’Éclipse');\n const total=damage+sealDamage;", 'blade_confirm')
rep("q('#newTurn').onclick=()=>{push();S.turn++;S.solHit=S.selHit=S.seal=false;S.solTarget=S.selTarget='';S.pendingHit=null;S.eldritchRun=null;S.lastCrit=false;S.lastCritBlade='';resetEconomy();if(S.sealTarget&&S.turn>S.sealExpiresAfterTurn){log(`✦ Le Sceau d’Éclipse sur ${S.sealTarget} expire.`);S.sealTarget='';S.sealExpiresAfterTurn=0}render();log(`↻ Tour ${S.turn} : Action, action bonus et réaction restaurées • suivi des touches réinitialisé.`)};", "q('#newTurn').onclick=()=>{push();const summary=endTurnSummary();S.turn++;S.solHit=S.selHit=S.seal=false;S.solTarget=S.selTarget='';S.pendingHit=null;S.eldritchRun=null;S.lastCrit=false;S.lastCritBlade='';resetEconomy();resetTurnSummary();if(S.sealTarget&&S.turn>S.sealExpiresAfterTurn){S.sealTarget='';S.sealExpiresAfterTurn=0}render();log(`${summary}\\n\\n↻ Tour ${S.turn} : Action, action bonus et réaction restaurées.`)};", 'new_turn')

p.write_text(text,encoding='utf-8')
print('PATCH_OK')
